import { findHeader, normalizeCell, normalizeHeader, readCsvMatrix, readXlsxMatrix } from "@/modules/accounts-payable/shared/spreadsheet";
import { normalizeOrganizationalValue } from "@/lib/organizational-label";
import { TRANSIT_VOUCHER_REQUIRED_COLUMNS, TRANSIT_VOUCHER_SHEET_NAME } from "./columns";

export type TransitVoucherField = "company" | "employeeName" | "serviceDate" | "department" | "service" | "costCenter" | "dailyAmount" | "previousMonthDifference" | "occasionalDiscounts" | "days" | "amount";
export type TransitVoucherRawRow = Record<TransitVoucherField, string | number | null>;
export type TransitVoucherFieldError = { field: TransitVoucherField; label: string; reason: "required" | "invalid" | "recommended"; message: string };
export type TransitVoucherRow = { sourceRow: number; identifier: string | null; employeeName: string; originalEmployeeName: string; company: string; department: string; serviceDate: string | null; service: string | null; costCenter: string | null; dailyAmount: string | null; previousMonthDifference: string | null; occasionalDiscounts: string | null; days: string | null; amount: string };
export type TransitVoucherIssue = { sourceRow: number | null; employeeName: string | null; code: string; message: string; rawData?: TransitVoucherRawRow; fieldErrors?: TransitVoucherFieldError[] };
export type TransitVoucherResult = { totalRows: number; allocations: TransitVoucherRow[]; issues: TransitVoucherIssue[]; blockingError?: string };
const aliases = { company: ["empresa"], name: ["nome", "colaborador", "nome colaborador"], date: ["data"], department: ["departamento", "setor"], service: ["servico", "serviço"], costCenter: ["cc", "centro de custo"], dailyAmount: ["valor dia"], previousDifference: ["dif mes anterior", "dif mês anterior"], discounts: ["descontos eventuais"], days: ["dias"], total: ["valor total", "total"], identifier: ["matricula", "matrícula", "cpf", "id", "codigo", "código"] };
export function normalizeTransitName(value: unknown) { return normalizeCell(value).toLocaleLowerCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g, ""); }
function rawValue(value: unknown): string | number | null { if (value === null || value === undefined || value === "") return null; if (value instanceof Date) return value.toISOString(); return typeof value === "number" ? value : normalizeCell(value); }
function decimalValue(value: unknown, scale = 4) { if (value === null || value === undefined || value === "") return null; if (typeof value === "number" && Number.isFinite(value)) return value.toFixed(scale); const cleaned = normalizeCell(value).replace(/[^\d.,-]/g, ""); if (!cleaned) return null; const normalized = cleaned.includes(",") ? cleaned.replace(/\./g, "").replace(",", ".") : cleaned; const parsed = Number(normalized); return Number.isFinite(parsed) ? parsed.toFixed(scale) : null; }
function dateValue(value: unknown) { if (value instanceof Date && !Number.isNaN(value.getTime())) return value.toISOString(); if (typeof value === "number" && Number.isFinite(value)) { const date = new Date(Date.UTC(1899, 11, 30) + Math.round(value * 86400000)); return Number.isNaN(date.getTime()) ? null : date.toISOString(); } const text = normalizeCell(value); if (!text) return null; if (/^\d{4,5}(?:[.,]\d+)?$/.test(text)) { const serial = Number(text.replace(",", ".")); return new Date(Date.UTC(1899, 11, 30) + Math.round(serial * 86400000)).toISOString(); } const br = text.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/); const date = br ? new Date(Date.UTC(Number(br[3]), Number(br[2]) - 1, Number(br[1]))) : new Date(text); return Number.isNaN(date.getTime()) ? null : date.toISOString(); }
function messageFor(errors: TransitVoucherFieldError[]) { return `Pendências: ${errors.map((error) => error.message).join("; ")}.`; }

function processMatrix(matrix: unknown[][]): TransitVoucherResult {
  if (!matrix.length) return { totalRows: 0, allocations: [], issues: [], blockingError: "O arquivo está vazio." };
  const headers = matrix[0].map(normalizeHeader); const at = (key: keyof typeof aliases) => findHeader(headers, aliases[key]);
  const indexes = { company: at("company"), name: at("name"), date: at("date"), department: at("department"), service: at("service"), costCenter: at("costCenter"), dailyAmount: at("dailyAmount"), previousDifference: at("previousDifference"), discounts: at("discounts"), days: at("days"), total: at("total"), identifier: at("identifier") };
  const requiredIndexes = { EMPRESA: indexes.company, NOME: indexes.name, DATA: indexes.date, DEPARTAMENTO: indexes.department, "VALOR TOTAL": indexes.total }; const missing = TRANSIT_VOUCHER_REQUIRED_COLUMNS.filter((column) => requiredIndexes[column] < 0);
  if (missing.length) return { totalRows: Math.max(0, matrix.length - 1), allocations: [], issues: [], blockingError: `Colunas obrigatórias ausentes: ${missing.join(", ")}.` };
  const allocations: TransitVoucherRow[] = []; const issues: TransitVoucherIssue[] = [];
  for (let index = 1; index < matrix.length; index++) {
    const values = matrix[index]; const sourceRow = index + 1; if (!values.some((value) => normalizeCell(value))) continue;
    const rawData: TransitVoucherRawRow = { company: rawValue(values[indexes.company]), employeeName: rawValue(values[indexes.name]), serviceDate: rawValue(values[indexes.date]), department: rawValue(values[indexes.department]), service: indexes.service >= 0 ? rawValue(values[indexes.service]) : null, costCenter: indexes.costCenter >= 0 ? rawValue(values[indexes.costCenter]) : null, dailyAmount: indexes.dailyAmount >= 0 ? rawValue(values[indexes.dailyAmount]) : null, previousMonthDifference: indexes.previousDifference >= 0 ? rawValue(values[indexes.previousDifference]) : null, occasionalDiscounts: indexes.discounts >= 0 ? rawValue(values[indexes.discounts]) : null, days: indexes.days >= 0 ? rawValue(values[indexes.days]) : null, amount: rawValue(values[indexes.total]) };
    const company = normalizeCell(rawData.company); const employeeName = normalizeCell(rawData.employeeName); const department = normalizeOrganizationalValue(rawData.department); const serviceDate = dateValue(rawData.serviceDate); const amount = decimalValue(rawData.amount); const dailyAmount = decimalValue(rawData.dailyAmount); const previousMonthDifference = decimalValue(rawData.previousMonthDifference); const occasionalDiscounts = decimalValue(rawData.occasionalDiscounts); const days = decimalValue(rawData.days, 2);
    const errors: TransitVoucherFieldError[] = [];
    if (!company) errors.push({ field: "company", label: "EMPRESA", reason: "required", message: "EMPRESA não informada" });
    if (!employeeName) errors.push({ field: "employeeName", label: "NOME", reason: "required", message: "NOME não informado" });
    if (!rawData.serviceDate) errors.push({ field: "serviceDate", label: "DATA", reason: "required", message: "DATA não informada" }); else if (!serviceDate) errors.push({ field: "serviceDate", label: "DATA", reason: "invalid", message: "DATA inválida" });
    if (!department) errors.push({ field: "department", label: "DEPARTAMENTO", reason: "required", message: "DEPARTAMENTO não informado" });
    if (amount === null) errors.push({ field: "amount", label: "VALOR TOTAL", reason: "invalid", message: "VALOR TOTAL inválido" });
    if (rawData.dailyAmount !== null && dailyAmount === null) errors.push({ field: "dailyAmount", label: "VALOR DIA", reason: "invalid", message: "VALOR DIA inválido" });
    if (rawData.previousMonthDifference !== null && previousMonthDifference === null) errors.push({ field: "previousMonthDifference", label: "DIF MÊS ANTERIOR", reason: "invalid", message: "DIF MÊS ANTERIOR inválida" });
    if (rawData.occasionalDiscounts !== null && occasionalDiscounts === null) errors.push({ field: "occasionalDiscounts", label: "DESCONTOS EVENTUAIS", reason: "invalid", message: "DESCONTOS EVENTUAIS inválidos" });
    if (rawData.days !== null && days === null) errors.push({ field: "days", label: "DIAS", reason: "invalid", message: "DIAS inválido" });
    if (errors.length) { if (!normalizeCell(rawData.service)) errors.push({ field: "service", label: "SERVIÇO", reason: "recommended", message: "SERVIÇO não informado" }); issues.push({ sourceRow, employeeName: employeeName || null, code: "ROW_REVIEW_REQUIRED", message: messageFor(errors), rawData, fieldErrors: errors }); continue; }
    allocations.push({ sourceRow, identifier: indexes.identifier >= 0 ? normalizeCell(values[indexes.identifier]) || null : null, employeeName, originalEmployeeName: employeeName, company, department, serviceDate, service: normalizeCell(rawData.service) || null, costCenter: normalizeOrganizationalValue(rawData.costCenter) || null, dailyAmount, previousMonthDifference, occasionalDiscounts, days, amount: amount! });
  }
  return { totalRows: Math.max(0, matrix.length - 1), allocations, issues };
}
export function parseTransitVoucherCsv(text: string) { return processMatrix(readCsvMatrix(text)); }
export async function parseTransitVoucherXlsx(buffer: Buffer) { return processMatrix(await readXlsxMatrix(buffer, TRANSIT_VOUCHER_SHEET_NAME)); }
export function normalizeTransitVoucherCorrection(raw: TransitVoucherRawRow) { const matrix = [["EMPRESA", "NOME", "DATA", "DEPARTAMENTO", "SERVIÇO", "CC", "VALOR DIA", "DIF MÊS ANTERIOR", "DESCONTOS EVENTUAIS", "DIAS", "VALOR TOTAL"], [raw.company, raw.employeeName, raw.serviceDate, raw.department, raw.service, raw.costCenter, raw.dailyAmount, raw.previousMonthDifference, raw.occasionalDiscounts, raw.days, raw.amount]]; return processMatrix(matrix); }
