import type { Colaborador } from "@/lib/types/payroll";

export const COLABORADOR_HEADERS = [
  "Empresa",
  "Código",
  "Nome",
  "CPF",
  "Admissão",
  "Situação",
  "Vínculo",
  "Horas Mês",
  "Departamento",
  "Centro de Custo",
  "Código do Cargo",
  "Cargo",
  "CBO",
  "Filial",
  "Salário",
  "Proventos",
  "Descontos",
  "Líquido",
  "Informativa",
  "Informativa Dedutora",
  "Base INSS",
  "Base FGTS",
  "Base IRRF",
  "Excedente INSS",
  "Valor FGTS",
  "Observações",
  "Campos com baixa confiança",
] as const;

export function colaboradorToRow(c: Colaborador): (string | number)[] {
  return [
    c.empresaNome || "",
    c.codigo,
    c.nome,
    c.cpf,
    c.admissao,
    c.situacao,
    c.vinculo,
    c.horasMes,
    c.departamento,
    c.centroCusto,
    c.cargoCodigo,
    c.cargo,
    c.cbo,
    c.filial,
    c.salario,
    c.proventos,
    c.descontos,
    c.liquido,
    c.informativa,
    c.informativaDedutora,
    c.baseINSS,
    c.baseFGTS,
    c.baseIRRF,
    c.excedenteINSS,
    c.valorFGTS,
    c.observacoes.join("; "),
    c.camposBaixaConfianca.join(", "),
  ];
}
