"use client";
import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { formatCnpj } from "@/modules/administrative-entities/schema";
import { Button, FileInput, type FileInputStatus } from "@/components/ui";

type Detail = { identifier: string; description: string | null; grossAmount: string; currency: string; documentState: string; extractionState: string; validationState: string; company: { legalName: string } | null; administrativeEntity: { cnpj: string | null; legalName: string; tradeName: string; activityArea: string; locality: string; appliesProjeta: boolean; appliesBoinga: boolean } };
type Doc = { id: string; kind: string; version: number; originalName: string; sizeBytes: number; active: boolean; createdAt: string };

export default function PaymentDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [detail, setDetail] = useState<Detail | null>(null); const [files, setFiles] = useState<Doc[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [fileName, setFileName] = useState(""); const [uploadStatus, setUploadStatus] = useState<FileInputStatus>("normal");
  async function loadFiles() { const response = await fetch(`/api/financial-records/${id}/files`); const body = await response.json(); if (!response.ok) throw new Error(body.error); setFiles(body.items ?? []); }
  useEffect(() => { Promise.all([fetch(`/api/financial-records/${id}`).then((r) => r.json()), fetch(`/api/financial-records/${id}/files`).then((r) => r.json())]).then(([record, documents]) => { setDetail(record.item); setFiles(documents.items ?? []); }).catch(() => setError("Não foi possível carregar o registro.")); }, [id]);
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; setBusy(true); setUploadStatus("normal"); setError(null); try { const response = await fetch(`/api/financial-records/${id}/files`, { method: "POST", body: new FormData(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); form.reset(); setUploadStatus("success"); await loadFiles(); setDetail((value) => value ? { ...value, documentState: "ATTACHED", extractionState: "QUEUED" } : value); } catch (cause) { setUploadStatus("error"); setError(cause instanceof Error ? cause.message : "Falha no upload."); } finally { setBusy(false); } }
  return <main className="max-w-6xl w-full mx-auto px-4 sm:px-6 py-8 flex flex-col gap-6">
    <Link href="/pagamentos" className="text-sm text-primary">← Contas a pagar</Link>
    <div><p className="font-mono text-primary">{detail?.identifier}</p><h1 className="text-2xl font-bold">{detail ? `Obrigação para ${detail.administrativeEntity.tradeName}` : "Carregando…"}</h1><p className="text-sm text-text-muted">Valor bruto: {detail ? new Intl.NumberFormat("pt-BR", { style: "currency", currency: detail.currency }).format(Number(detail.grossAmount)) : "—"}</p></div>
    {detail && <div className="card grid gap-3 p-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><span className="block text-xs text-text-muted">Razão social</span><strong>{detail.administrativeEntity.legalName}</strong></div><div><span className="block text-xs text-text-muted">CNPJ</span><strong>{formatCnpj(detail.administrativeEntity.cnpj)}</strong></div><div><span className="block text-xs text-text-muted">Área / Localidade</span><strong>{detail.administrativeEntity.activityArea} · {detail.administrativeEntity.locality}</strong></div><div><span className="block text-xs text-text-muted">Aplicabilidade</span><strong>Projeta: {detail.administrativeEntity.appliesProjeta ? "SIM" : "NÃO"} · Boinga: {detail.administrativeEntity.appliesBoinga ? "SIM" : "NÃO"}</strong></div></div>}
    <div className="grid grid-cols-3 gap-3">{[["Documento", detail?.documentState], ["Extração", detail?.extractionState], ["Validação", detail?.validationState]].map(([label, value]) => <div key={label} className="card p-4"><p className="text-xs text-text-muted">{label}</p><p className="font-semibold">{value ?? "—"}</p></div>)}</div>
    <Link href={`/pagamentos/${id}/validacao`} className="self-start rounded-md bg-primary px-4 py-2 text-sm font-medium text-white">Abrir validação documental</Link>
    <form onSubmit={upload} className="card p-5 grid md:grid-cols-[1fr_auto_auto] gap-3 items-end"><label className="text-sm"><span className="block text-xs text-text-muted mb-1">Novo documento</span><FileInput required name="file" accept=".pdf,.jpg,.jpeg,.png,.xml,.xlsx" fileName={fileName} loading={busy} status={uploadStatus === "loading" ? "normal" : uploadStatus} aria-label="Selecionar novo documento" onChange={(event) => { const selected = event.target.files?.[0]; setFileName(selected?.name ?? ""); setUploadStatus("normal"); setError(null); }} /></label><select name="kind" defaultValue="TAX_INVOICE" disabled={busy} className="rounded-md border border-border px-3 py-2"><option value="TAX_INVOICE">Nota fiscal</option><option value="INVOICE">Invoice</option><option value="BOLETO">Boleto</option><option value="RECEIPT">Comprovante</option><option value="XML">XML</option><option value="SPREADSHEET">Planilha</option><option value="SUPPORTING">Auxiliar</option><option value="OTHER">Outro</option></select><Button type="submit" loading={busy} aura>{"Enviar"}</Button></form>
    {error && <p className="rounded-md border border-danger/30 p-3 text-danger">{error}</p>}
    <section className="card"><h2 className="p-4 border-b border-border font-semibold">Histórico documental</h2>{files.map((file) => <div key={file.id} className="flex items-center justify-between gap-3 p-4 border-b border-border last:border-0"><a className="text-primary hover:underline" href={`/api/financial-files/${file.id}`} target="_blank">{file.originalName}<span className="block text-xs text-text-muted">{file.kind} · v{file.version} · {(file.sizeBytes / 1024).toFixed(1)} KB</span></a><div className="flex items-center gap-2"><span className="text-xs">{file.active ? "Atual" : "Substituído"}</span><Button variant="ghost" size="sm" onClick={async () => { await fetch(`/api/financial-files/${file.id}/reprocess`, { method: "POST" }); setDetail((value) => value ? { ...value, extractionState: "QUEUED" } : value); }}>Reprocessar</Button></div></div>)}{files.length === 0 && <p className="p-8 text-center text-text-muted">Nenhum documento anexado.</p>}</section>
  </main>;
}
