import { normalizeFoodDepartment, normalizeFoodName } from "./ma-processing";
export type MatchEmployee={id:string;officialName:string;normalizedName:string;department:string;costCenter?:string;jobTitle?:string};
type Alias={normalizedAlias:string;employee:MatchEmployee};
export type FoodMatchMethod="UNMATCHED"|"EXACT"|"NORMALIZED"|"ALIAS"|"FUZZY";
export type MatchConfidence="HIGH"|"MEDIUM"|"LOW"|"AMBIGUOUS"|"NOT_FOUND";
export type RankedCollaborator={employee:MatchEmployee;score:number;reasons:string[]};
export type CollaboratorMatch={employee:MatchEmployee|null;method:FoodMatchMethod;bestCandidate:RankedCollaborator|null;alternatives:RankedCollaborator[];score:number;confidence:MatchConfidence;reasons:string[];isAmbiguous:boolean};
const connectors=new Set(["de","da","do","das","dos","e"]);
export const tokenizeCollaboratorName=(value:string)=>normalizeFoodName(value).split(" ").filter(token=>token&&!connectors.has(token));
function distance(a:string,b:string){const previous=Array.from({length:b.length+1},(_,index)=>index);for(let i=1;i<=a.length;i++){let diagonal=previous[0];previous[0]=i;for(let j=1;j<=b.length;j++){const above=previous[j];previous[j]=Math.min(previous[j]+1,previous[j-1]+1,diagonal+Number(a[i-1]!==b[j-1]));diagonal=above}}return previous[b.length]}
const similarity=(a:string,b:string)=>a&&b?1-distance(a,b)/Math.max(a.length,b.length):0;
const same=(a?:string,b?:string)=>Boolean(a&&b&&normalizeFoodDepartment(a)===normalizeFoodDepartment(b));
function rankCandidate(receivedName:string,receivedDepartment:string,receivedCostCenter:string|undefined,receivedJobTitle:string|undefined,employee:MatchEmployee):RankedCollaborator{const received=tokenizeCollaboratorName(receivedName),official=tokenizeCollaboratorName(employee.officialName),reasons:string[]=[];if(!received.length||!official.length)return{employee,score:0,reasons};const first=similarity(received[0],official[0]),last=similarity(received.at(-1)!,official.at(-1)!);const coverage=received.reduce((sum,token)=>sum+Math.max(...official.map(candidate=>similarity(token,candidate))),0)/received.length;let cursor=-1;const ordered=received.every(token=>{const next=official.findIndex((candidate,index)=>index>cursor&&similarity(token,candidate)>=.84);if(next<0)return false;cursor=next;return true});const full=similarity(received.join(" "),official.join(" "));const department=same(receivedDepartment,employee.department),costCenter=same(receivedCostCenter,employee.costCenter),jobTitle=same(receivedJobTitle,employee.jobTitle);let score=first*.28+last*.23+coverage*.27+full*.08+(ordered?.07:0)+(department?.10:0)+(costCenter?.025:0)+(jobTitle?.015:0);if(first<.72)score*=.58;if(received.length===1)score=Math.min(score,.67);score=Math.min(1,score);if(first>=.98)reasons.push("Primeiro nome correspondente");else if(first>=.82)reasons.push("Primeiro nome muito semelhante");if(last>=.98)reasons.push("Último sobrenome correspondente");else if(last>=.82)reasons.push("Sobrenome muito semelhante");if(coverage>=.98)reasons.push(`${received.length} de ${received.length} palavras recebidas encontradas`);else if(coverage>=.82)reasons.push("Palavras do nome muito semelhantes");if(ordered)reasons.push("Ordem dos nomes preservada");if(department)reasons.push("Departamento correspondente");if(costCenter)reasons.push("Centro de custo correspondente");if(jobTitle)reasons.push("Função correspondente");return{employee,score,reasons}}
export function matchCollaborator(input:{receivedName:string;receivedDepartment?:string;receivedCostCenter?:string;receivedJobTitle?:string;collaborators:MatchEmployee[];aliases?:Alias[]}):CollaboratorMatch{const name=normalizeFoodName(input.receivedName),department=input.receivedDepartment??"",aliases=input.aliases??[];const aliasMatches=aliases.filter(item=>item.normalizedAlias===name);if(aliasMatches.length){const preferred=aliasMatches.filter(item=>same(department,item.employee.department));const unique=(preferred.length===1?preferred:aliasMatches.length===1?aliasMatches:[])[0];if(unique){const ranked={employee:unique.employee,score:1,reasons:["Alias conhecido"]};return{employee:unique.employee,method:"ALIAS",bestCandidate:ranked,alternatives:[ranked],score:1,confidence:"HIGH",reasons:ranked.reasons,isAmbiguous:false}}}const normalized=input.collaborators.filter(employee=>employee.normalizedName===name);if(normalized.length===1){const employee=normalized[0],ranked={employee,score:1,reasons:["Nome oficial normalizado exato"]};return{employee,method:employee.officialName.trim()===input.receivedName.trim()?"EXACT":"NORMALIZED",bestCandidate:ranked,alternatives:[ranked],score:1,confidence:"HIGH",reasons:ranked.reasons,isAmbiguous:false}}const ranked=input.collaborators.map(employee=>rankCandidate(input.receivedName,department,input.receivedCostCenter,input.receivedJobTitle,employee)).sort((a,b)=>b.score-a.score||a.employee.officialName.localeCompare(b.employee.officialName,"pt-BR")||a.employee.id.localeCompare(b.employee.id));const best=ranked[0]??null,second=ranked[1]??null,margin=best?best.score-(second?.score??0):0;const short=tokenizeCollaboratorName(input.receivedName).length<=2,threshold=short?.75:.82,minMargin=short?.09:.07;const ambiguous=Boolean(best&&best.score>=.66&&second&&margin<minMargin);const automatic=Boolean(best&&best.score>=threshold&&margin>=minMargin);const confidence:MatchConfidence=!best||best.score<.5?"NOT_FOUND":ambiguous?"AMBIGUOUS":automatic?"HIGH":best.score>=.68?"MEDIUM":"LOW";return{employee:automatic?best!.employee:null,method:automatic?"FUZZY":"UNMATCHED",bestCandidate:best,alternatives:ranked.slice(0,3),score:best?.score??0,confidence,reasons:best?.reasons??[],isAmbiguous:ambiguous}}
export function matchFoodEmployee(receivedName:string,receivedDepartment:string,employees:MatchEmployee[],aliases:Alias[]){return matchCollaborator({receivedName,receivedDepartment,collaborators:employees,aliases})}
