import "server-only";
import { Prisma } from "@/generated/prisma";
import { prisma } from "@/lib/db/prisma";
import { parseCollaboratorInput,type CollaboratorInput } from "./schema";
import { classifyCollaborator,parseCollaboratorWorkbook } from "./import";
import { recalculateFoodBatch,recalculateTransitMap } from "@/modules/accounts-payable/deletion-server";
export class CollaboratorValidationError extends Error {}
const employeeSelect={id:true,officialName:true,normalizedName:true,jobTitle:true,department:true,costCenter:true,active:true} as const;
export async function previewCollaboratorImport(buffer:Buffer){
 const[parsed,existing,aliases]=await Promise.all([parseCollaboratorWorkbook(buffer),prisma.foodEmployee.findMany({where:{mergedIntoId:null},select:employeeSelect}),prisma.foodEmployeeAlias.findMany()]);
 const rows=parsed.map(row=>{const result=classifyCollaborator(row.data,existing);const alias=aliases.find(item=>item.normalizedAlias===row.data.normalizedName);const aliasMatch=alias?existing.find(item=>item.id===alias.employeeId):null;return{...row,...(aliasMatch?{classification:"POSSIBLE_DUPLICATE" as const,match:aliasMatch,score:1}:result)}});
 return{total:rows.length,counts:rows.reduce((counts,row)=>({...counts,[row.classification]:(counts[row.classification]??0)+1}),{} as Record<string,number>),rows};
}
type Decision={sourceRow:number;data:CollaboratorInput;action:"CREATE"|"KEEP"|"UPDATE";targetId?:string};
export async function confirmCollaboratorImport(decisions:Decision[]){if(!decisions.length)throw new CollaboratorValidationError("Nenhum registro para importar.");return prisma.$transaction(async tx=>{let created=0,updated=0,kept=0;for(const decision of decisions){const data=parseCollaboratorInput(decision.data);if(decision.action==="KEEP"){kept++;continue}if(decision.action==="CREATE"){const exists=await tx.foodEmployee.findUnique({where:{normalizedName:data.normalizedName}});if(exists)throw new CollaboratorValidationError(`A linha ${decision.sourceRow} já corresponde a ${exists.officialName}.`);await tx.foodEmployee.create({data});created++;continue}if(!decision.targetId)throw new CollaboratorValidationError(`Selecione o cadastro existente da linha ${decision.sourceRow}.`);const profile={officialName:data.officialName,normalizedName:data.normalizedName,jobTitle:data.jobTitle,department:data.department,costCenter:data.costCenter};await tx.foodEmployee.update({where:{id:decision.targetId},data:profile});updated++}return{created,updated,kept}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function collaboratorReferenceCounts(id:string,client:Prisma.TransactionClient|typeof prisma=prisma){const[food,transit,aliases,mergedEmployees]=await Promise.all([client.foodMealOccurrence.count({where:{employeeId:id}}),client.transitVoucherAllocation.count({where:{employeeId:id}}),client.foodEmployeeAlias.count({where:{employeeId:id}}),client.foodEmployee.count({where:{mergedIntoId:id}})]);return{food,transit,aliases,mergedEmployees,total:food+transit+aliases+mergedEmployees}}
export async function mergeCollaborators(primaryId:string,secondaryId:string){if(!primaryId||!secondaryId||primaryId===secondaryId)throw new CollaboratorValidationError("Selecione dois colaboradores diferentes.");return prisma.$transaction(async tx=>{const[primary,secondary]=await Promise.all([tx.foodEmployee.findUnique({where:{id:primaryId}}),tx.foodEmployee.findUnique({where:{id:secondaryId}})]);if(!primary||!secondary||primary.mergedIntoId||secondary.mergedIntoId)throw new CollaboratorValidationError("Colaborador não encontrado ou já mesclado.");const counts=await collaboratorReferenceCounts(secondaryId,tx);await tx.foodMealOccurrence.updateMany({where:{employeeId:secondaryId},data:{employeeId:primaryId}});await tx.transitVoucherAllocation.updateMany({where:{employeeId:secondaryId},data:{employeeId:primaryId}});await tx.foodEmployeeAlias.updateMany({where:{employeeId:secondaryId},data:{employeeId:primaryId}});if(secondary.normalizedName!==primary.normalizedName)await tx.foodEmployeeAlias.upsert({where:{normalizedAlias:secondary.normalizedName},create:{employeeId:primaryId,sourceName:secondary.officialName,normalizedAlias:secondary.normalizedName},update:{employeeId:primaryId}});await tx.foodEmployee.update({where:{id:secondaryId},data:{active:false,mergedIntoId:primaryId}});return{primary,secondary:{...secondary,active:false,mergedIntoId:primaryId},transferred:counts}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export type CollaboratorDeletionAnalysis={total:number;deletable:number;withHistory:number;items:Array<{id:string;officialName:string;action:"DELETE"|"DEACTIVATE";references:{food:number;transit:number;aliases:number;mergedEmployees:number}}>};
async function analyzeWithClient(client:Prisma.TransactionClient|typeof prisma,ids?:string[]):Promise<CollaboratorDeletionAnalysis>{const unique=ids?[...new Set(ids.filter(Boolean))]:undefined;if(unique&&!unique.length)throw new CollaboratorValidationError("Selecione ao menos um colaborador.");const employees=await client.foodEmployee.findMany({where:unique?{id:{in:unique}}:{},select:{id:true,officialName:true}});if(unique&&employees.length!==unique.length)throw new CollaboratorValidationError("Um ou mais colaboradores não foram encontrados.");const items=[];for(const employee of employees){const references=await collaboratorReferenceCounts(employee.id,client);const hasHistory=references.food>0||references.transit>0||references.mergedEmployees>0;items.push({id:employee.id,officialName:employee.officialName,action:hasHistory?"DEACTIVATE" as const:"DELETE" as const,references})}return{total:items.length,deletable:items.filter(item=>item.action==="DELETE").length,withHistory:items.filter(item=>item.action==="DEACTIVATE").length,items}}
export async function analyzeCollaboratorDeletion(ids?:string[]){return analyzeWithClient(prisma,ids)}
export async function deleteCollaboratorsBatch(ids?:string[]){return prisma.$transaction(async tx=>{const analysis=await analyzeWithClient(tx,ids);const deletableIds=analysis.items.filter(item=>item.action==="DELETE").map(item=>item.id);const protectedIds=analysis.items.filter(item=>item.action==="DEACTIVATE").map(item=>item.id);if(deletableIds.length)await tx.foodEmployee.deleteMany({where:{id:{in:deletableIds}}});if(protectedIds.length)await tx.foodEmployee.updateMany({where:{id:{in:protectedIds}},data:{active:false}});return{...analysis,deleted:deletableIds.length,deactivated:protectedIds.length}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function deleteCollaborator(id:string){const result=await deleteCollaboratorsBatch([id]);return{deleted:result.deleted===1,deactivated:result.deactivated===1,references:result.items[0]?.references}}
export type CollaboratorPurgeAnalysis={total:number;foodOccurrences:number;transitAllocations:number;aliases:number;mergedLinks:number;foodBatches:number;transitMaps:number;advancedFinancialRecords:number;items:Array<{id:string;officialName:string;food:number;transit:number;aliases:number}>};
async function analyzePurgeWithClient(client:Prisma.TransactionClient|typeof prisma,ids?:string[]):Promise<CollaboratorPurgeAnalysis>{const unique=ids?[...new Set(ids.filter(Boolean))]:undefined;if(unique&&!unique.length)throw new CollaboratorValidationError("Selecione ao menos um colaborador.");const employees=await client.foodEmployee.findMany({where:unique?{id:{in:unique}}:{},select:{id:true,officialName:true}});if(unique&&employees.length!==unique.length)throw new CollaboratorValidationError("Um ou mais colaboradores não foram encontrados.");const employeeIds=employees.map(item=>item.id);if(!employeeIds.length)return{total:0,foodOccurrences:0,transitAllocations:0,aliases:0,mergedLinks:0,foodBatches:0,transitMaps:0,advancedFinancialRecords:0,items:[]};const[foodRows,transitRows,aliasRows,mergedLinks,batches,maps]=await Promise.all([client.foodMealOccurrence.groupBy({by:["employeeId"],where:{employeeId:{in:employeeIds}},_count:true}),client.transitVoucherAllocation.groupBy({by:["employeeId"],where:{employeeId:{in:employeeIds}},_count:true}),client.foodEmployeeAlias.groupBy({by:["employeeId"],where:{employeeId:{in:employeeIds}},_count:true}),client.foodEmployee.count({where:{mergedIntoId:{in:employeeIds}}}),client.foodBatch.findMany({where:{mealOccurrences:{some:{employeeId:{in:employeeIds}}}},select:{id:true,financialRecord:{select:{lifecycleState:true,paymentState:true,reconciliationState:true,accountingState:true}}}}),client.transitVoucherMap.findMany({where:{allocations:{some:{employeeId:{in:employeeIds}}}},select:{id:true,financialRecord:{select:{lifecycleState:true,paymentState:true,reconciliationState:true,accountingState:true}}}})]);const count=(rows:Array<{employeeId:string|null;_count:number}>,id:string)=>rows.find(row=>row.employeeId===id)?._count??0;const items=employees.map(employee=>({id:employee.id,officialName:employee.officialName,food:count(foodRows,employee.id),transit:count(transitRows,employee.id),aliases:count(aliasRows,employee.id)}));const advanced=(record:{lifecycleState:string;paymentState:string;reconciliationState:string;accountingState:string}|null)=>Boolean(record&&(record.lifecycleState!=="ACTIVE"||record.paymentState!=="PENDING"||record.reconciliationState!=="PENDING"||record.accountingState!=="PENDING"));return{total:employees.length,foodOccurrences:foodRows.reduce((sum,row)=>sum+row._count,0),transitAllocations:transitRows.reduce((sum,row)=>sum+row._count,0),aliases:aliasRows.reduce((sum,row)=>sum+row._count,0),mergedLinks,foodBatches:batches.length,transitMaps:maps.length,advancedFinancialRecords:[...batches,...maps].filter(item=>advanced(item.financialRecord)).length,items}}
export async function analyzeCollaboratorPurge(ids?:string[]){return analyzePurgeWithClient(prisma,ids)}
export async function purgeCollaborators(ids?:string[]){return prisma.$transaction(async tx=>{const analysis=await analyzePurgeWithClient(tx,ids);const allEmployees=await tx.foodEmployee.count();const fullPurge=analysis.total===allEmployees;if(analysis.advancedFinancialRecords&&!fullPurge)throw new CollaboratorValidationError(`${analysis.advancedFinancialRecords} obrigação(ões) já avançaram no fluxo financeiro. Use Limpar base para cancelá-las de forma integral.`);const employeeIds=analysis.items.map(item=>item.id);if(!employeeIds.length)return{...analysis,deleted:0};const[foodBatchRows,transitMapRows]=await Promise.all([tx.foodBatch.findMany({where:{mealOccurrences:{some:{employeeId:{in:employeeIds}}}},select:{id:true,financialRecordId:true}}),tx.transitVoucherMap.findMany({where:{allocations:{some:{employeeId:{in:employeeIds}}}},select:{id:true,financialRecordId:true}})]);await tx.foodEmployeeAlias.deleteMany({where:{employeeId:{in:employeeIds}}});await tx.foodMealOccurrence.deleteMany({where:{employeeId:{in:employeeIds}}});await tx.transitVoucherAllocation.deleteMany({where:{employeeId:{in:employeeIds}}});await tx.foodEmployee.updateMany({where:{mergedIntoId:{in:employeeIds}},data:{mergedIntoId:null}});const deleted=await tx.foodEmployee.deleteMany({where:{id:{in:employeeIds}}});if(fullPurge){const now=new Date(),foodBatchIds=foodBatchRows.map(row=>row.id),transitMapIds=transitMapRows.map(row=>row.id),financialIds=[...new Set([...foodBatchRows,...transitMapRows].map(row=>row.financialRecordId).filter((id):id is string=>Boolean(id)))];if(foodBatchIds.length){await tx.foodAllocation.deleteMany({where:{batchId:{in:foodBatchIds}}});await tx.foodBatch.updateMany({where:{id:{in:foodBatchIds}},data:{current:false,cancelledAt:now,validRows:0,totalAmount:0,cancellationReason:"Limpeza administrativa da base de colaboradores"}})}if(transitMapIds.length)await tx.transitVoucherMap.updateMany({where:{id:{in:transitMapIds}},data:{current:false,cancelledAt:now,validRows:0,totalAmount:0,cancellationReason:"Limpeza administrativa da base de colaboradores"}});if(financialIds.length){await tx.approvalRequest.updateMany({where:{financialRecordId:{in:financialIds},active:true},data:{active:false,status:"CANCELLED",completedAt:now}});await tx.financialRecord.updateMany({where:{id:{in:financialIds}},data:{grossAmount:0,netAmount:0,lifecycleState:"CANCELLED",paymentState:"CANCELLED",notes:"Cancelado pela limpeza administrativa da base de colaboradores."}})}}else{for(const row of foodBatchRows)await recalculateFoodBatch(tx,row.id);for(const row of transitMapRows)await recalculateTransitMap(tx,row.id)}return{...analysis,deleted:deleted.count,cancelledFinancialRecords:fullPurge?[...new Set([...foodBatchRows,...transitMapRows].map(row=>row.financialRecordId).filter(Boolean))].length:0}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable,maxWait:10000,timeout:120000})}
export async function findDuplicateCandidates(){const employees=await prisma.foodEmployee.findMany({where:{mergedIntoId:null},select:employeeSelect,orderBy:{officialName:"asc"}});const pairs=[];for(let left=0;left<employees.length;left++)for(let right=left+1;right<employees.length;right++){const result=classifyCollaborator(employees[left],employees.filter(item=>item.id===employees[right].id));if(result.classification==="POSSIBLE_DUPLICATE"||result.classification==="EXISTING")pairs.push({left:employees[left],right:employees[right],score:result.score})}return pairs.sort((a,b)=>b.score-a.score)}
export async function bulkSetCollaboratorStatus(ids:string[],active:boolean){const unique=[...new Set(ids.filter(Boolean))];if(!unique.length)throw new CollaboratorValidationError("Selecione ao menos um colaborador.");return prisma.foodEmployee.updateMany({where:{id:{in:unique},mergedIntoId:null},data:{active}})}
