import "server-only";
import { Prisma } from "@/generated/prisma";
import { prisma } from "@/lib/db/prisma";
import { CpfValidationError } from "@/lib/cpf";
import { DateOnlyValidationError } from "@/lib/date-only";
import { classifyCollaborator,generateCollaboratorTemplate,parseCollaboratorWorkbook,planCollaboratorImport,type ImportOverride,type PlannedImportRow } from "./import";
import { recalculateFoodBatch,recalculateTransitMap } from "@/modules/accounts-payable/deletion-server";
export class CollaboratorValidationError extends Error {}
const employeeSelect={id:true,officialName:true,normalizedName:true,jobTitle:true,department:true,costCenter:true,active:true} as const;
export const CPF_IN_USE_MESSAGE="Já existe um colaborador cadastrado com este CPF.";
// Erro de escrita conhecido → mensagem de negócio (nunca o erro técnico do banco, nem o CPF).
export async function collaboratorWriteError(error:unknown):Promise<{message:string;status:number}|null>{if(error instanceof CpfValidationError||error instanceof DateOnlyValidationError)return{message:error.message,status:400};if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002"){const target=JSON.stringify(error.meta??{});return{message:/cpf/i.test(target)?CPF_IN_USE_MESSAGE:"Já existe um colaborador cadastrado com este nome.",status:409}}return null}
const importCandidateSelect={...employeeSelect,cpf:true,admissionDate:true,mergedIntoId:true} as const;
export class CollaboratorImportBlockedError extends CollaboratorValidationError{constructor(public rows:PlannedImportRow[]){super(`Importação bloqueada: ${rows.length} linha(s) com erro. Corrija a planilha e analise novamente.`)}}
type Client=Prisma.TransactionClient|typeof prisma;
async function planImport(client:Client,buffer:Buffer,overrides:Record<number,ImportOverride>){const[rows,existing,aliases]=await Promise.all([parseCollaboratorWorkbook(buffer),client.foodEmployee.findMany({select:importCandidateSelect}),client.foodEmployeeAlias.findMany({select:{normalizedAlias:true,employeeId:true}})]);return planCollaboratorImport(rows,existing,aliases,overrides)}
// Resposta da prévia: sem dados internos de escrita; CPF de cadastros existentes só mascarado.
const publicRow=({create:_create,update:_update,...row}:PlannedImportRow)=>{void _create;void _update;return row};
export async function previewCollaboratorImport(buffer:Buffer,overrides:Record<number,ImportOverride>={}){const plan=await planImport(prisma,buffer,overrides);return{...plan,rows:plan.rows.map(publicRow)}}
// Confirmação: reprocessa o MESMO arquivo no servidor (não confia em dados da prévia), valida tudo e
// só então grava, numa única transação Serializable — qualquer erro aborta sem escrita parcial.
// Só toca FoodEmployee: configs (VT/Café), aliases, lançamentos e snapshots históricos ficam intactos.
export async function confirmCollaboratorImport(buffer:Buffer,overrides:Record<number,ImportOverride>={}){return prisma.$transaction(async tx=>{const plan=await planImport(tx,buffer,overrides);if(!plan.total)throw new CollaboratorValidationError("Nenhum registro para importar.");if(plan.blocked)throw new CollaboratorImportBlockedError(plan.rows.filter(row=>row.status==="ERROR"));let created=0,updated=0;for(const row of plan.rows){if(row.create){await tx.foodEmployee.create({data:row.create});created++}else if(row.update){await tx.foodEmployee.update({where:{id:row.update.id},data:row.update.data});updated++}}return{total:plan.total,created,updated,unchanged:plan.counts.UNCHANGED,skipped:plan.counts.REVIEW+plan.counts.SKIP,errors:0}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable,maxWait:10000,timeout:120000})}
export async function collaboratorTemplate(){return generateCollaboratorTemplate(await prisma.foodEmployee.findMany({where:{mergedIntoId:null},select:{id:true,officialName:true,jobTitle:true,department:true,costCenter:true,cpf:true,admissionDate:true},orderBy:{officialName:"asc"}}))}
export async function collaboratorReferenceCounts(id:string,client:Prisma.TransactionClient|typeof prisma=prisma){const[food,transit,aliases,mergedEmployees]=await Promise.all([client.foodMealOccurrence.count({where:{employeeId:id}}),client.transitVoucherAllocation.count({where:{employeeId:id}}),client.foodEmployeeAlias.count({where:{employeeId:id}}),client.foodEmployee.count({where:{mergedIntoId:id}})]);return{food,transit,aliases,mergedEmployees,total:food+transit+aliases+mergedEmployees}}
export async function mergeCollaborators(primaryId:string,secondaryId:string){if(!primaryId||!secondaryId||primaryId===secondaryId)throw new CollaboratorValidationError("Selecione dois colaboradores diferentes.");return prisma.$transaction(async tx=>{const[primary,secondary]=await Promise.all([tx.foodEmployee.findUnique({where:{id:primaryId}}),tx.foodEmployee.findUnique({where:{id:secondaryId}})]);if(!primary||!secondary||primary.mergedIntoId||secondary.mergedIntoId)throw new CollaboratorValidationError("Colaborador não encontrado ou já mesclado.");const counts=await collaboratorReferenceCounts(secondaryId,tx);await tx.foodMealOccurrence.updateMany({where:{employeeId:secondaryId},data:{employeeId:primaryId}});await tx.transitVoucherAllocation.updateMany({where:{employeeId:secondaryId},data:{employeeId:primaryId}});await tx.foodEmployeeAlias.updateMany({where:{employeeId:secondaryId},data:{employeeId:primaryId}});if(secondary.normalizedName!==primary.normalizedName)await tx.foodEmployeeAlias.upsert({where:{normalizedAlias:secondary.normalizedName},create:{employeeId:primaryId,sourceName:secondary.officialName,normalizedAlias:secondary.normalizedName},update:{employeeId:primaryId}});await tx.foodEmployee.update({where:{id:secondaryId},data:{active:false,mergedIntoId:primaryId}});return{primary,secondary:{...secondary,active:false,mergedIntoId:primaryId},transferred:counts}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export type CollaboratorDeletionAnalysis={total:number;deletable:number;withHistory:number;items:Array<{id:string;officialName:string;action:"DELETE"|"DEACTIVATE";references:{food:number;transit:number;aliases:number;mergedEmployees:number}}>};
async function analyzeWithClient(client:Prisma.TransactionClient|typeof prisma,ids?:string[]):Promise<CollaboratorDeletionAnalysis>{const unique=ids?[...new Set(ids.filter(Boolean))]:undefined;if(unique&&!unique.length)throw new CollaboratorValidationError("Selecione ao menos um colaborador.");const employees=await client.foodEmployee.findMany({where:unique?{id:{in:unique}}:{},select:{id:true,officialName:true}});if(unique&&employees.length!==unique.length)throw new CollaboratorValidationError("Um ou mais colaboradores não foram encontrados.");const items=[];for(const employee of employees){const references=await collaboratorReferenceCounts(employee.id,client);const hasHistory=references.food>0||references.transit>0||references.mergedEmployees>0;items.push({id:employee.id,officialName:employee.officialName,action:hasHistory?"DEACTIVATE" as const:"DELETE" as const,references})}return{total:items.length,deletable:items.filter(item=>item.action==="DELETE").length,withHistory:items.filter(item=>item.action==="DEACTIVATE").length,items}}
export async function analyzeCollaboratorDeletion(ids?:string[]){return analyzeWithClient(prisma,ids)}
export async function deleteCollaboratorsBatch(ids?:string[]){return prisma.$transaction(async tx=>{const analysis=await analyzeWithClient(tx,ids);const deletableIds=analysis.items.filter(item=>item.action==="DELETE").map(item=>item.id);const protectedIds=analysis.items.filter(item=>item.action==="DEACTIVATE").map(item=>item.id);if(deletableIds.length)await tx.foodEmployee.deleteMany({where:{id:{in:deletableIds}}});if(protectedIds.length)await tx.foodEmployee.updateMany({where:{id:{in:protectedIds}},data:{active:false}});return{...analysis,deleted:deletableIds.length,deactivated:protectedIds.length}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function deleteCollaborator(id:string){const result=await deleteCollaboratorsBatch([id]);return{deleted:result.deleted===1,deactivated:result.deactivated===1,references:result.items[0]?.references}}
export type CollaboratorPurgeAnalysis={total:number;foodOccurrences:number;transitAllocations:number;aliases:number;mergedLinks:number;foodBatches:number;transitMaps:number;advancedFinancialRecords:number;items:Array<{id:string;officialName:string;food:number;transit:number;aliases:number}>};
async function analyzePurgeWithClient(client:Prisma.TransactionClient|typeof prisma,ids?:string[]):Promise<CollaboratorPurgeAnalysis>{const unique=ids?[...new Set(ids.filter(Boolean))]:undefined;if(unique&&!unique.length)throw new CollaboratorValidationError("Selecione ao menos um colaborador.");const employees=await client.foodEmployee.findMany({where:unique?{id:{in:unique}}:{},select:{id:true,officialName:true}});if(unique&&employees.length!==unique.length)throw new CollaboratorValidationError("Um ou mais colaboradores não foram encontrados.");const employeeIds=employees.map(item=>item.id);if(!employeeIds.length)return{total:0,foodOccurrences:0,transitAllocations:0,aliases:0,mergedLinks:0,foodBatches:0,transitMaps:0,advancedFinancialRecords:0,items:[]};const[foodRows,transitRows,aliasRows,mergedLinks,batches,maps]=await Promise.all([client.foodMealOccurrence.groupBy({by:["employeeId"],where:{employeeId:{in:employeeIds}},_count:true}),client.transitVoucherAllocation.groupBy({by:["employeeId"],where:{employeeId:{in:employeeIds}},_count:true}),client.foodEmployeeAlias.groupBy({by:["employeeId"],where:{employeeId:{in:employeeIds}},_count:true}),client.foodEmployee.count({where:{mergedIntoId:{in:employeeIds}}}),client.foodBatch.findMany({where:{mealOccurrences:{some:{employeeId:{in:employeeIds}}}},select:{id:true,financialRecord:{select:{lifecycleState:true,paymentState:true,reconciliationState:true,accountingState:true}}}}),client.transitVoucherMap.findMany({where:{allocations:{some:{employeeId:{in:employeeIds}}}},select:{id:true,financialRecord:{select:{lifecycleState:true,paymentState:true,reconciliationState:true,accountingState:true}}}})]);const count=(rows:Array<{employeeId:string|null;_count:number}>,id:string)=>rows.find(row=>row.employeeId===id)?._count??0;const items=employees.map(employee=>({id:employee.id,officialName:employee.officialName,food:count(foodRows,employee.id),transit:count(transitRows,employee.id),aliases:count(aliasRows,employee.id)}));const advanced=(record:{lifecycleState:string;paymentState:string;reconciliationState:string;accountingState:string}|null)=>Boolean(record&&(record.lifecycleState!=="ACTIVE"||record.paymentState!=="PENDING"||record.reconciliationState!=="PENDING"||record.accountingState!=="PENDING"));return{total:employees.length,foodOccurrences:foodRows.reduce((sum,row)=>sum+row._count,0),transitAllocations:transitRows.reduce((sum,row)=>sum+row._count,0),aliases:aliasRows.reduce((sum,row)=>sum+row._count,0),mergedLinks,foodBatches:batches.length,transitMaps:maps.length,advancedFinancialRecords:[...batches,...maps].filter(item=>advanced(item.financialRecord)).length,items}}
export async function analyzeCollaboratorPurge(ids?:string[]){return analyzePurgeWithClient(prisma,ids)}
export async function purgeCollaborators(ids?:string[]){return prisma.$transaction(async tx=>{const analysis=await analyzePurgeWithClient(tx,ids);const allEmployees=await tx.foodEmployee.count();const fullPurge=analysis.total===allEmployees;if(analysis.advancedFinancialRecords&&!fullPurge)throw new CollaboratorValidationError(`${analysis.advancedFinancialRecords} obrigação(ões) já avançaram no fluxo financeiro. Use Limpar base para cancelá-las de forma integral.`);const employeeIds=analysis.items.map(item=>item.id);if(!employeeIds.length)return{...analysis,deleted:0};const[foodBatchRows,transitMapRows]=await Promise.all([tx.foodBatch.findMany({where:{mealOccurrences:{some:{employeeId:{in:employeeIds}}}},select:{id:true,financialRecordId:true}}),tx.transitVoucherMap.findMany({where:{allocations:{some:{employeeId:{in:employeeIds}}}},select:{id:true,financialRecordId:true}})]);await tx.foodEmployeeAlias.deleteMany({where:{employeeId:{in:employeeIds}}});await tx.foodMealOccurrence.deleteMany({where:{employeeId:{in:employeeIds}}});await tx.transitVoucherAllocation.deleteMany({where:{employeeId:{in:employeeIds}}});await tx.foodEmployee.updateMany({where:{mergedIntoId:{in:employeeIds}},data:{mergedIntoId:null}});const deleted=await tx.foodEmployee.deleteMany({where:{id:{in:employeeIds}}});if(fullPurge){const now=new Date(),foodBatchIds=foodBatchRows.map(row=>row.id),transitMapIds=transitMapRows.map(row=>row.id),financialIds=[...new Set([...foodBatchRows,...transitMapRows].map(row=>row.financialRecordId).filter((id):id is string=>Boolean(id)))];if(foodBatchIds.length){await tx.foodAllocation.deleteMany({where:{batchId:{in:foodBatchIds}}});await tx.foodBatch.updateMany({where:{id:{in:foodBatchIds}},data:{current:false,cancelledAt:now,validRows:0,totalAmount:0,cancellationReason:"Limpeza administrativa da base de colaboradores"}})}if(transitMapIds.length)await tx.transitVoucherMap.updateMany({where:{id:{in:transitMapIds}},data:{current:false,cancelledAt:now,validRows:0,totalAmount:0,cancellationReason:"Limpeza administrativa da base de colaboradores"}});if(financialIds.length){await tx.approvalRequest.updateMany({where:{financialRecordId:{in:financialIds},active:true},data:{active:false,status:"CANCELLED",completedAt:now}});await tx.financialRecord.updateMany({where:{id:{in:financialIds}},data:{grossAmount:0,netAmount:0,lifecycleState:"CANCELLED",paymentState:"CANCELLED",notes:"Cancelado pela limpeza administrativa da base de colaboradores."}})}}else{for(const row of foodBatchRows)await recalculateFoodBatch(tx,row.id);for(const row of transitMapRows)await recalculateTransitMap(tx,row.id)}return{...analysis,deleted:deleted.count,cancelledFinancialRecords:fullPurge?[...new Set([...foodBatchRows,...transitMapRows].map(row=>row.financialRecordId).filter(Boolean))].length:0}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable,maxWait:10000,timeout:120000})}
export async function findDuplicateCandidates(){const employees=await prisma.foodEmployee.findMany({where:{mergedIntoId:null},select:employeeSelect,orderBy:{officialName:"asc"}});const pairs=[];for(let left=0;left<employees.length;left++)for(let right=left+1;right<employees.length;right++){const result=classifyCollaborator(employees[left],employees.filter(item=>item.id===employees[right].id));if(result.classification==="POSSIBLE_DUPLICATE"||result.classification==="EXISTING")pairs.push({left:employees[left],right:employees[right],score:result.score})}return pairs.sort((a,b)=>b.score-a.score)}
export async function bulkSetCollaboratorStatus(ids:string[],active:boolean){const unique=[...new Set(ids.filter(Boolean))];if(!unique.length)throw new CollaboratorValidationError("Selecione ao menos um colaborador.");return prisma.foodEmployee.updateMany({where:{id:{in:unique},mergedIntoId:null},data:{active}})}
