"use client";
import { createPortal } from "react-dom";
import { useEffect,useLayoutEffect,useRef,useState,type ReactNode } from "react";
type Props={open:boolean;onOpenChange:(open:boolean)=>void;label:string;children:ReactNode};
export function FloatingActionMenu({open,onOpenChange,label,children}:Props){
 const trigger=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null);const[position,setPosition]=useState({top:0,left:0,visibility:"hidden" as "hidden"|"visible"});const[portalRoot,setPortalRoot]=useState<Element|null>(null);
 useLayoutEffect(()=>{if(!open||!trigger.current)return;setPortalRoot(trigger.current.closest("dialog")??document.body);const rect=trigger.current.getBoundingClientRect(),width=176,height=180,gap=6;const above=window.innerHeight-rect.bottom<height&&rect.top>height;setPosition({top:above?Math.max(8,rect.top-height-gap):Math.min(window.innerHeight-height-8,rect.bottom+gap),left:Math.max(8,Math.min(window.innerWidth-width-8,rect.right-width)),visibility:"visible"})},[open]);
 useEffect(()=>{if(!open)return;const close=(event:MouseEvent)=>{if(!menu.current?.contains(event.target as Node)&&!trigger.current?.contains(event.target as Node))onOpenChange(false)};const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){onOpenChange(false);trigger.current?.focus()}};const reposition=()=>onOpenChange(false);document.addEventListener("mousedown",close);document.addEventListener("keydown",key);window.addEventListener("resize",reposition);window.addEventListener("scroll",reposition,true);requestAnimationFrame(()=>menu.current?.querySelector<HTMLElement>("button")?.focus());return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",key);window.removeEventListener("resize",reposition);window.removeEventListener("scroll",reposition,true)}},[open,onOpenChange]);
 return <><button ref={trigger} type="button" className="btn btn-ghost btn-sm" aria-label={label} aria-haspopup="menu" aria-expanded={open} onClick={()=>onOpenChange(!open)}>•••</button>{open&&portalRoot&&createPortal(<div ref={menu} role="menu" style={position} className="fixed z-40 w-44 rounded-lg border border-base-300 bg-base-100 p-1 shadow-xl" onClick={()=>onOpenChange(false)}>{children}</div>,portalRoot)}</>;
}
